target = muti_thread

objs = /home/hxk/C++Project/C++11webserver/code/log/*.cpp /home/hxk/C++Project/C++11webserver/test/log/mutithread/mutithread.cpp

$(target) : $(objs)
	$(CXX) $(objs) -o $(target)